---
  ##apiVersion: extensions/v1beta1
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kanboard
    namespace: ns-kanboard
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: kanboard
    template:
      metadata:
        labels:
          run: kanboard
      spec:
        volumes:
        - name: kanboard-data
          persistentVolumeClaim:
            claimName: kanboard-data
        - name: kanboard-plugins
          persistentVolumeClaim:
            claimName: kanboard-plugins
        - name: kanboard-ssl
          persistentVolumeClaim:
            claimName: kanboard-ssl
        containers:
        - env:
          - name: DEBUG
            value: 'true'
          - name: DATABASE_URL
            value: 'mysql://kanboarduser:mysqlsecret@dbkanboard-service/kanboard'
          name: kanboard
          image: kanboard/kanboard:latest
          ports:
          - containerPort: 80
          - containerPort: 443
          volumeMounts:
          - mountPath: "/var/www/app/data"
            name: kanboard-data
          - mountPath: "/var/www/app/plugins"
            name: kanboard-plugins
          - mountPath: "/etc/nginx/ssl"
            name: kanboard-ssl
  status: {}